### ISSUE TITLE
Rendering error

### ISSUE THREAD

**Issue by dani-lbnl** [CameraIA/microct_skimage#1]
jupyter notebook no rendering correctly
![Screenshot 2019-11-03 21 09 09](https://user-images.githubusercontent.com/8379306/68100707-447eb600-fe7e-11e9-88c9-b36557c792e1.png)

**Comment by alexdesiqueira** [comment]
I guess this is related to `<div class=\"alert alert-success\">`; I'll look into that.

**Comment by alexdesiqueira** [comment]
Solved; coming back to normal Markdown formatting.
